# Generated by Django 3.2.7 on 2021-09-27 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210927_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='signup_confirmation',
        ),
    ]
