# Generated by Django 3.2.7 on 2021-09-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20210923_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
